export const BATTLEDATA = [
  {
    id: 1,
    title: '강철의 늑대들',
    genre: 'battle',
    image: "https://picsum.photos/id/20/300/300"
  },
  {
    id: 2,
    title: '군인장기',
    genre: 'battle',
    image: "https://picsum.photos/id/20/300/300",  
  },
  {
    id: 3,
    title: '눈 덮힌 좁은 땅(A Few Acres of Snow)',
    genre: 'battle',
    image: "https://picsum.photos/id/200/300/300",
  },
  {
    id: 4,
    title: '디플로메시',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 5,
    title: '리스크(보드 게임)',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 6,
    title: '루트(보드게임)',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 7,
    title: '매누버',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 8,
    title: '메모아 44',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 9,
    title: '메크 대 미니언',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 10,
    title: '바르바로사: 키예프 에서 로스토프로, 1941',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 11,
    title: '반지의 제왕: 대결',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 12,
    title: '배틀 크라이',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 13,
    title: '스코틀랜드의 망치 (해머오브스콧)',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 14,
    title: '승리와 비극',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 15,
    title: '썬더볼트 아파치 리더',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 16,
    title: '영광의 길 (패스오브글로리)',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 17,
    title: '월드 앳 워(보드 게임)',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 18,
    title: '일러전쟁',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 19,
    title: '처녀 여왕(보드 게임)',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 20,
    title: '컴뱃 커멘더 시리즈',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 21,
    title: '코바야카와(보드 게임)',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 22,
    title: '필드 커맨더 : 나폴레옹',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 23,
    title: '하이브(보드 게임)',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 24,
    title: '호넷 리더',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 25,
    title: 'Axis and Allies 시리즈',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 26,
    title: 'Commands and Colors Ancients (커맨드앤컬러스 에인션트)',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 27,
    title: 'Commands and Colors Napoleonics (커맨드앤컬러스 나폴레오닉)',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 28,
    title: 'WW2: 바르바로사 투 베를린',
    genre: 'battle',
    image: "https://picsum.photos/id/1000/300/300",
  },

]