export const ECONOMICDATA = [
  {
    id: 1,
    title: '갤러리스트',
    genre: 'economic',
    image: "https://picsum.photos/id/20/300/300"
  },
  {
    id: 2,
    title: '고속도로 노선 골든게임',
    genre: 'economic',
    image: "https://picsum.photos/id/20/300/300",  
  },
  {
    id: 3,
    title: '더 시티',
    genre: 'economic',
    image: "https://picsum.photos/id/200/300/300",
  },
  {
    id: 4,
    title: '러시안 레일로드',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 5,
    title: '르아브르(보드 게임)',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 6,
    title: '마닐라',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 7,
    title: '맨해튼 프로잭트 : 에너지 앰파이어',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 8,
    title: '모노폴리',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 9,
    title: '모던 아트',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 10,
    title: '몸바사(보드 게임)',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 11,
    title: '미니빌',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 12,
    title: '번레이트',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 13,
    title: '보난자',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 14,
    title: '부루마불',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 15,
    title: '부자만들기',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 16,
    title: '상트페테르부르크(보드 게임)',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 17,
    title: '산후안(보드 게임)',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 18,
    title: '아그리콜라',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 19,
    title: '어콰이어',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 20,
    title: '에이지 오브 스팀',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 21,
    title: '오딘을 위한 잔치(한글판 발매명 : 오딘을 위하여)',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 22,
    title: '인생게임',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 23,
    title: '인생역전',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 24,
    title: '자이푸르',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 25,
    title: '지하철 노선 골든게임',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 26,
    title: '카탄',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 27,
    title: '테라포밍 마스',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 28,
    title: '티켓 투 라이드(보드 게임)',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 29,
    title: '파워 그리드',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 30,
    title: '푸에르토 리코',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 31,
    title: '카베르나: 동굴 속 농부들',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 32,
    title: '호텔왕게임',
    genre: 'economic',
    image: "https://picsum.photos/id/1000/300/300",
  },
 
]