export const FANTASYHORRORDATA = [
  {
    id: 1,
    title: '광기의 저택',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/20/300/300"
  },
  {
    id: 2,
    title: '광기의 저택 2판',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/20/300/300",  
  },
  {
    id: 3,
    title: '글룸헤이븐',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/200/300/300",
  },
  {
    id: 4,
    title: '다크 소울: 더 보드 게임',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 5,
    title: '던전 앤 드래곤 어드벤쳐 시스템 보드 게임',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 6,
    title: '데드 오브 윈터',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 7,
    title: '도라스레',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 8,
    title: '드래곤파이어(보드 게임)',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 9,
    title: '디 아더스: 세븐 신즈',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 10,
    title: '룬에이지',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 11,
    title: '매시브 다크니스',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 12,
    title: '메이지 나이트',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 13,
    title: '먼치킨(보드 게임)',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 14,
    title: '반지의 제왕: 듀얼',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 15,
    title: '배틀로어',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 16,
    title: '블러드 바운드',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 17,
    title: '블러드 레이지',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 18,
    title: '블러드본: 더 카드 게임',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 19,
    title: '블레이드 론도',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 20,
    title: '소드 앤 소서리',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 21,
    title: '스몰 월드',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 22,
    title: '스타 렐름',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 23,
    title: '아브라카...왓?',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 24,
    title: '아컴호러',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 25,
    title: '악마성의 마차',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 26,
    title: '언덕 위 집의 배신',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 27,
    title: '엘드리치 호러',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 28,
    title: '와글와글 던전',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 29,
    title: '왕좌의 게임 (게임오브쓰론)',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 30,
    title: '웨스테로스의 전투',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 31,
    title: '월드 오브 워크래프트 TCG',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 32,
    title: '좀비사이드',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 33,
    title: '카멜롯의 그림자',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 34,
    title: '카후나',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 36,
    title: '콜로설 아레나',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 37,
    title: '크툴루 워즈',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 38,
    title: '크툴루 죽음마저 죽으리니',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 39,
    title: '탈리스만(보드 게임)',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 40,
    title: '테라 미스티카',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 41,
    title: '패스파인더 어드벤처 카드 게임',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 42,
    title: 'Ascension',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 43,
    title: 'Aeon\'s End:Legacy',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 44,
    title: 'Elder Sign',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 45,
    title: 'Thud!',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 46,
    title: 'Warhammer',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },
  {
    id: 47,
    title: '5분 던전',
    genre: 'fantasyhorror',
    image: "https://picsum.photos/id/1000/300/300",
  },

]